name: Gateway CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Run Linters & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Install latest golangci-lint (v1.64.7)
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.7
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Run Linters
        run: golangci-lint run ./...

      - name: Run Unit Tests
        run: go test ./... -cover

  build-and-push:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest
    needs: lint-and-test  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t injus/scn-gateway:latest .
      - name: Push Docker Image to Docker Hub
        run: |
          docker push injus/scn-gateway:latest
